FROM multiarch/alpine:armhf-v3.8
MAINTAINER "Tyler Christiansen <code@tylerc.me>"

ARG BLACK_VERSION=latest

RUN adduser -D black

RUN apk --no-cache add \
    py3-pip \
  && pip3 install --upgrade pip \
  && [ "${BLACK_VERSION}" = "latest" ] \
     && \
       pip3 install black \
     || \
       pip3 install black=="${BLACK_VERSION}" \
  && rm -rf /usr/share/man/man1 \
  && rm -rf /usr/share/man/man7 \
  && rm -rf /tmp/*

VOLUME ["/code"]

USER black
WORKDIR /code

ENTRYPOINT ["black"]
